export const pillNames = [
  "Aspirin",
  "Ibuprofen",
  "Paracetamol",
  "Amoxicillin",
  "Metformin",
  "Lisinopril",
  "Atorvastatin",
  "Omeprazole",
  "Levothyroxine",
  "Azithromycin",
  "Losartan",
  "Prednisone",
  "Gabapentin",
  "Hydrochlorothiazide",
  "Sertraline",
  "Citalopram",
  "Fluoxetine",
  "Simvastatin",
  "Warfarin",
  "Clopidogrel",
  "Metoprolol",
  "Amlodipine",
  "Furosemide",
  "Pantoprazole",
  "Tramadol",
  "Codeine",
  "Doxycycline",
  "Clindamycin",
  "Cephalexin",
  "Naproxen",
  "Melatonin",
  "Vitamin D",
  "Calcium Carbonate",
  "Magnesium",
  "Iron Supplement",
  "Folic Acid",
  "Zinc",
  "Biotin",
  "Multivitamin",
  "Fish Oil",
  "Probiotic",
  "Loratadine",
  "Cetirizine",
  "Diphenhydramine",
  "Montelukast",
  "Alprazolam",
  "Diazepam",
  "Insulin",
  "Glipizide",
  "Bupropion",
];

// String id, String name, String relation, boolean isSelf

export const mockProfiles = [
  { id: "11122sdjxjhxj2", name: "Azeez", relation: "SELF", isSelf: true },
  { id: "113sjhj44873628", name: "Mike", relation: "FATHER", isSelf: false },
  { id: "11e883wjhsjhuww2", name: "Lola", relation: "SISTER", isSelf: false },
  {
    id: "11shjhjhsjsjdjsjsj",
    name: "Emily",
    relation: "MOTHER",
    isSelf: false,
  },
];

export const mockUser = {
  id: "12345678-absj-shdhjd",
  email: "azeezabiola@ail.com",
  name: "Azeez Abiola",
  gender: "MALE",
  profiles: [],
};
