export const pillNames = [
  "Aspirin",
  "Ibuprofen",
  "Paracetamol",
  "Amoxicillin",
  "Metformin",
  "Lisinopril",
  "Atorvastatin",
  "Omeprazole",
  "Levothyroxine",
  "Azithromycin",
  "Losartan",
  "Prednisone",
  "Gabapentin",
  "Hydrochlorothiazide",
  "Sertraline",
  "Citalopram",
  "Fluoxetine",
  "Simvastatin",
  "Warfarin",
  "Clopidogrel",
  "Metoprolol",
  "Amlodipine",
  "Furosemide",
  "Pantoprazole",
  "Tramadol",
  "Codeine",
  "Doxycycline",
  "Clindamycin",
  "Cephalexin",
  "Naproxen",
  "Melatonin",
  "Vitamin D",
  "Calcium Carbonate",
  "Magnesium",
  "Iron Supplement",
  "Folic Acid",
  "Zinc",
  "Biotin",
  "Multivitamin",
  "Fish Oil",
  "Probiotic",
  "Loratadine",
  "Cetirizine",
  "Diphenhydramine",
  "Montelukast",
  "Alprazolam",
  "Diazepam",
  "Insulin",
  "Glipizide",
  "Bupropion",
];

export const mockProfiles = [
  { name: "Mike", relation: "FATHER" },
  { name: "Lola", relation: "SISTER" },
  { name: "Emily", relation: "MOTHER" },
];
