import { DosageMeasurement, MedicationScheduleResponse, ProfileResponse } from "./types/medication";
export const pillNames = [
  "Aspirin",
  "Ibuprofen",
  "Paracetamol",
  "Amoxicillin",
  "Metformin",
  "Lisinopril",
  "Atorvastatin",
  "Omeprazole",
  "Levothyroxine",
  "Azithromycin",
  "Losartan",
  "Prednisone",
  "Gabapentin",
  "Hydrochlorothiazide",
  "Sertraline",
  "Citalopram",
  "Fluoxetine",
  "Simvastatin",
  "Warfarin",
  "Clopidogrel",
  "Metoprolol",
  "Amlodipine",
  "Furosemide",
  "Pantoprazole",
  "Tramadol",
  "Codeine",
  "Doxycycline",
  "Clindamycin",
  "Cephalexin",
  "Naproxen",
  "Melatonin",
  "Vitamin D",
  "Calcium Carbonate",
  "Magnesium",
  "Iron Supplement",
  "Folic Acid",
  "Zinc",
  "Biotin",
  "Multivitamin",
  "Fish Oil",
  "Probiotic",
  "Loratadine",
  "Cetirizine",
  "Diphenhydramine",
  "Montelukast",
  "Alprazolam",
  "Diazepam",
  "Insulin",
  "Glipizide",
  "Bupropion",
];

export const mockProfiles: ProfileResponse[] = [
  {
    id: "eef65956-af4e-46c6-9363-bc1613b966c2",
    name: "Azeez",
    relation: "SELF",
    isSelf: true,
  },
  { id: "113sjhj44873628", name: "Mike", relation: "FATHER", isSelf: false },
  { id: "11e883wjhsjhuww2", name: "Lola", relation: "SISTER", isSelf: false },
  {
    id: "11shjhjhsjsjdjsjsj",
    name: "Emily",
    relation: "MOTHER",
    isSelf: false,
  },
];

export const mockUser = {
  id: "12345678-absj-shdhjd",
  email: "azeezabiola@ail.com",
  name: "Azeez Abiola",
  gender: "MALE",
  profiles: [],
};

export const mockMedicationsSchedule: MedicationScheduleResponse[] = [
  {
    id: "1",
    status: "PENDING",
    medicationName: "Ibuprofen",
    medicationImageUrl: "https://picsum.photos/seed/ibuprofen/100/100",
    dosage: 1.0,
    measurement: DosageMeasurement.TABLET,
    scheduleAt: "2026-04-27T09:00",
    profile: {
      id: "p1",
      name: "Azeez",
      relation: "SELF",
      isSelf: true,
    },
    takenAt: null,
  },
  {
    id: "2",
    status: "TAKEN",
    medicationName: "Paracetamol",
    medicationImageUrl: "https://picsum.photos/seed/paracetamol/100/100",
    dosage: 2.0,
    measurement: DosageMeasurement.TABLET,
    scheduleAt: "2026-04-27T13:00",
    profile: {
      id: "p2",
      name: "Fatima",
      relation: "WIFE",
      isSelf: false,
    },
    takenAt: "2026-04-27T13:05",
  },
  {
    id: "3",
    status: "MISSED",
    medicationName: "Amoxicillin",
    medicationImageUrl: "https://picsum.photos/seed/amoxicillin/100/100",
    dosage: 1.0,
    measurement: DosageMeasurement.CAPSULE,
    scheduleAt: "2026-04-27T08:00",
    profile: {
      id: "p3",
      name: "Yusuf",
      relation: "SON",
      isSelf: false,
    },
    takenAt: null,
  },
  {
    id: "4",
    status: "PENDING",
    medicationName: "Metformin",
    medicationImageUrl: "https://picsum.photos/seed/metformin/100/100",
    dosage: 0.5,
    measurement: DosageMeasurement.TABLET,
    scheduleAt: "2026-04-27T18:30",
    profile: {
      id: "p4",
      name: "Amina",
      relation: "MOTHER",
      isSelf: false,
    },
    takenAt: null,
  },
  {
    id: "5",
    status: "TAKEN",
    medicationName: "Atorvastatin",
    medicationImageUrl: "https://picsum.photos/seed/atorvastatin/100/100",
    dosage: 1.0,
    measurement: DosageMeasurement.TABLET,
    scheduleAt: "2026-04-27T21:00",
    profile: {
      id: "p5",
      name: "Ibrahim",
      relation: "FATHER",
      isSelf: false,
    },
    takenAt: "2026-04-27T21:10",
  },
  {
    id: "6",
    status: "PENDING",
    medicationName: "Lisinopril",
    medicationImageUrl: "https://picsum.photos/seed/lisinopril/100/100",
    dosage: 1.0,
    measurement: DosageMeasurement.TABLET,
    scheduleAt: "2026-04-28T08:30",
    profile: {
      id: "p1",
      name: "Azeez",
      relation: "SELF",
      isSelf: true,
    },
    takenAt: null,
  },
  {
    id: "7",
    status: "MISSED",
    medicationName: "Omeprazole",
    medicationImageUrl: "https://picsum.photos/seed/omeprazole/100/100",
    dosage: 1.0,
    measurement: DosageMeasurement.TABLET,
    scheduleAt: "2026-04-28T07:00",
    profile: {
      id: "p2",
      name: "Fatima",
      relation: "WIFE",
      isSelf: false,
    },
    takenAt: null,
  },
  {
    id: "8",
    status: "TAKEN",
    medicationName: "Cetirizine",
    medicationImageUrl: "https://picsum.photos/seed/cetirizine/100/100",
    dosage: 1.0,
    measurement: DosageMeasurement.TABLET,
    scheduleAt: "2026-04-28T10:00",
    profile: {
      id: "p6",
      name: "Zainab",
      relation: "DAUGHTER",
      isSelf: false,
    },
    takenAt: "2026-04-28T10:02",
  },
  {
    id: "9",
    status: "PENDING",
    medicationName: "Pantoprazole",
    medicationImageUrl: "https://picsum.photos/seed/pantoprazole/100/100",
    dosage: 2.0,
    measurement: DosageMeasurement.TABLET,
    scheduleAt: "2026-04-28T11:30",
    profile: {
      id: "p1",
      name: "Maria",
      relation: "SELF",
      isSelf: true,
    },
    takenAt: null,
  },
  {
    id: "10",
    status: "PENDING",
    medicationName: "Aspirin",
    medicationImageUrl: "https://picsum.photos/seed/aspirin/100/100",
    dosage: 1.0,
    measurement: DosageMeasurement.CAPSULE,
    scheduleAt: "2026-04-28T20:00",
    profile: {
      id: "p3",
      name: "Yusuf",
      relation: "SON",
      isSelf: false,
    },
    takenAt: null,
  },
];
